server:
  port: 8080

spring:
  config:
    import: application-secret.yml
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none  # 필요에 따라 create, update, validate, none 선택
    show-sql: true  # 콘솔에서 실행되는 SQL 보기
    properties:
      hibernate:
        format_sql: true  # SQL을 보기 좋게 출력

  sql:
    init:
      mode: always # MySQL에서 data.sql, schema.sql 자동 적용하기 위한 설정
      encoding: UTF-8



# Swagger
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /login

# Exception handler

error:
  printStackTrace: true # Stack trace 출력 여부
  printStackTraceLine: 10 # Stack trace 출력 줄 수

logging:
  file:
    name:  # 비워서 spring.log 비활성화